[build]
  publish = "output"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/payment-intent"
  to = "/.netlify/functions/create-payment-intent"
  status = 200
  force = true

[[redirects]]
  from = "/api/create-order"
  to = "/.netlify/functions/create-order"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/menu.html"
  status = 200
